/**
 * Site genelindeki oyun kataloğu.
 * Ana sayfa kartlarını buradan üretir. Yeni oyun eklerken tek yapılacak:
 * buraya bir girdi ekleyip vite.config.ts içine sayfayı tanıtmak.
 */

export type GameStatus = 'ready' | 'soon'

export interface GameEntry {
  /** Klasör adıyla aynı olmalı: games/<id>/ */
  id: string
  title: string
  tagline: string
  emoji: string
  /** Ana sayfaya göre göreli yol. */
  href: string
  tags: string[]
  status: GameStatus
}

export const SITE_TITLE = 'Ali Kerem Oyunları'
export const SITE_TAGLINE = 'Tarayıcıda oynanan mini oyunlar'

export const GAMES: GameEntry[] = [
  {
    id: '2048',
    title: '2048',
    tagline: 'Kareleri kaydır, aynı sayıları birleştir ve 2048 karesine ulaş.',
    emoji: '🔢',
    href: 'games/2048/index.html',
    tags: ['Bulmaca', 'Tek kişilik'],
    status: 'ready',
  },
  {
    id: 'yilan',
    title: 'Yılan',
    tagline: 'Yem topla, uzadıkça hızlan. Duvara ve kuyruğuna çarpma.',
    emoji: '🐍',
    href: 'games/yilan/index.html',
    tags: ['Arcade', 'Refleks'],
    status: 'ready',
  },
  {
    id: 'tetris',
    title: 'Tetris',
    tagline: 'Düşen blokları yerleştir, satırları doldurup temizle.',
    emoji: '🧱',
    href: 'games/tetris/index.html',
    tags: ['Arcade', 'Refleks'],
    status: 'ready',
  },
  {
    id: 'mayin',
    title: 'Mayın Tarlası',
    tagline: 'Sayıları oku, mayınları bayrakla, tarlayı temizle.',
    emoji: '💣',
    href: 'games/mayin/index.html',
    tags: ['Mantık', 'Sabır'],
    status: 'ready',
  },
  {
    id: 'sudoku',
    title: 'Sudoku',
    tagline: 'Her satır, sütun ve kutuda 1-9 bir kez geçsin.',
    emoji: '🧮',
    href: 'games/sudoku/index.html',
    tags: ['Mantık', 'Üç zorluk'],
    status: 'ready',
  },
  {
    id: 'puzzle15',
    title: "15'li Kaydırmalı Puzzle",
    tagline: 'Karışan taşları kaydırarak 1’den 15’e sırala.',
    emoji: '🧩',
    href: 'games/puzzle15/index.html',
    tags: ['Bulmaca', 'Sakin'],
    status: 'ready',
  },
  {
    id: 'bulmaca',
    title: 'Kelime Bulmaca',
    tagline: 'İpuçlarını oku, kesişen kelimeleri harf harf doldur.',
    emoji: '📝',
    href: 'games/bulmaca/index.html',
    tags: ['Kelime', 'Mantık'],
    status: 'ready',
  },
  {
    id: 'kelimeavi',
    title: 'Kelime Avı',
    tagline: 'Harf karmaşasında gizlenen kelimeleri bul ve işaretle.',
    emoji: '🔎',
    href: 'games/kelimeavi/index.html',
    tags: ['Kelime', 'Dikkat'],
    status: 'ready',
  },
  {
    id: 'asmaca',
    title: 'Adam Asmaca',
    tagline: 'Harf tahmin et, altı hakkın bitmeden kelimeyi çöz.',
    emoji: '🪢',
    href: 'games/asmaca/index.html',
    tags: ['Kelime', 'Tahmin'],
    status: 'ready',
  },
  {
    id: 'lightsout',
    title: 'Lights Out',
    tagline: 'Bir kareye bas, komşuları da değişsin. Bütün ışıkları söndür.',
    emoji: '💡',
    href: 'games/lightsout/index.html',
    tags: ['Mantık', 'Sakin'],
    status: 'ready',
  },
  {
    id: 'hanoi',
    title: 'Hanoi Kuleleri',
    tagline: 'Diskleri kurallara uyarak son çubuğa taşı.',
    emoji: '🗼',
    href: 'games/hanoi/index.html',
    tags: ['Mantık', 'Klasik'],
    status: 'ready',
  },
  {
    id: 'mastermind',
    title: 'Mastermind',
    tagline: 'Gizli renk dizisini ipuçlarıyla adım adım çöz.',
    emoji: '🎯',
    href: 'games/mastermind/index.html',
    tags: ['Mantık', 'Tahmin'],
    status: 'ready',
  },
  {
    id: 'wordle',
    title: 'Wordle',
    tagline: 'Altı hakta beş harfli gizli kelimeyi bul.',
    emoji: '🟩',
    href: 'games/wordle/index.html',
    tags: ['Kelime', 'Tahmin'],
    status: 'ready',
  },
  {
    id: 'labirent',
    title: 'Labirent',
    tagline: 'Rastgele üretilen labirentte çıkışa ulaş.',
    emoji: '🧭',
    href: 'games/labirent/index.html',
    tags: ['Bulmaca', 'Keşif'],
    status: 'ready',
  },
  {
    id: 'sokoban',
    title: 'Sokoban',
    tagline: 'Kutuları iterek hedeflere yerleştir.',
    emoji: '📦',
    href: 'games/sokoban/index.html',
    tags: ['Mantık', 'Klasik'],
    status: 'ready',
  },
  {
    id: 'topsirala',
    title: 'Top Sıralama',
    tagline: 'Renkli topları tüplere ayır, her tüp tek renk olsun.',
    emoji: '🫧',
    href: 'games/topsirala/index.html',
    tags: ['Mantık', 'Sakin'],
    status: 'ready',
  },
  {
    id: 'nonogram',
    title: 'Nonogram',
    tagline: 'Kenardaki ipuçlarına göre resmi ortaya çıkar.',
    emoji: '🔲',
    href: 'games/nonogram/index.html',
    tags: ['Mantık', 'Resim'],
    status: 'ready',
  },
  {
    id: 'hafiza',
    title: 'Hafıza Kartları',
    tagline: 'Kartları çevir, eşleri bul, en az hamleyle bitir.',
    emoji: '🃏',
    href: 'games/hafiza/index.html',
    tags: ['Hafıza', 'Sakin'],
    status: 'ready',
  },
  {
    id: 'eslestirme',
    title: 'Eşleştirme Oyunu',
    tagline: 'Hayvan-yavrusu, ülke-başkent gibi ikilileri eşleştir.',
    emoji: '🔗',
    href: 'games/eslestirme/index.html',
    tags: ['Bilgi', 'Eşleştirme'],
    status: 'ready',
  },
  {
    id: 'sayipiramidi',
    title: 'Sayı Piramidi',
    tagline: 'Her taş altındaki iki taşın toplamı; eksikleri tamamla.',
    emoji: '🔺',
    href: 'games/sayipiramidi/index.html',
    tags: ['Matematik', 'Mantık'],
    status: 'ready',
  },
  {
    id: 'matematik',
    title: 'Matematik Bulmacası',
    tagline: 'Verilen sayıları işlemlerle birleştirip hedefi yakala.',
    emoji: '➗',
    href: 'games/matematik/index.html',
    tags: ['Matematik', 'Zekâ'],
    status: 'ready',
  },
  {
    id: 'renksirala',
    title: 'Renk Sıralama',
    tagline: 'Karışan renkleri sütunlara ayır.',
    emoji: '🎨',
    href: 'games/renksirala/index.html',
    tags: ['Mantık', 'Sakin'],
    status: 'ready',
  },
  {
    id: 'susise',
    title: 'Su Şişesi Renk Ayırma',
    tagline: 'Renkli suları dökerek her şişeyi tek renk yap.',
    emoji: '🧪',
    href: 'games/susise/index.html',
    tags: ['Mantık', 'Sakin'],
    status: 'ready',
  },
  {
    id: 'boru',
    title: 'Boru Bağlama',
    tagline: 'Boruları çevirip kaynaktan hedefe kesintisiz yol kur.',
    emoji: '🔧',
    href: 'games/boru/index.html',
    tags: ['Mantık', 'Bağlantı'],
    status: 'ready',
  },
  {
    id: 'suborusu',
    title: 'Su Borusu Yönlendirme',
    tagline: 'Boruları döndürerek suyu kaynaktan depoya ulaştır.',
    emoji: '🚰',
    href: 'games/suborusu/index.html',
    tags: ['Mantık', 'Bağlantı'],
    status: 'ready',
  },
  {
    id: 'devre',
    title: 'Elektrik Devresi',
    tagline: 'Kabloları döndürüp akımı bütün ampullere ulaştır.',
    emoji: '💡',
    href: 'games/devre/index.html',
    tags: ['Mantık', 'Bağlantı'],
    status: 'ready',
  },
  {
    id: 'kutuitme',
    title: 'Box Push',
    tagline: 'Sokoban’ın farklı bölümleri: kutuları hedeflere it.',
    emoji: '🧰',
    href: 'games/kutuitme/index.html',
    tags: ['Mantık', 'Klasik'],
    status: 'ready',
  },
  {
    id: 'lazer',
    title: 'Laser Reflection',
    tagline: 'Aynaları çevirerek lazer ışınını hedefe düşür.',
    emoji: '🔺',
    href: 'games/lazer/index.html',
    tags: ['Mantık', 'Işık'],
    status: 'ready',
  },
  {
    id: 'ayna',
    title: 'Aynalarla Lazer',
    tagline: 'Ayna açılarını ayarlayıp ışığı hedeflerden geçir.',
    emoji: '🪞',
    href: 'games/ayna/index.html',
    tags: ['Mantık', 'Işık'],
    status: 'ready',
  },
  {
    id: 'match3',
    title: 'Match-3',
    tagline: 'Komşu taşları değiştir, üçlü dizip patlat.',
    emoji: '💠',
    href: 'games/match3/index.html',
    tags: ['Arcade', 'Eşleştirme'],
    status: 'ready',
  },
  {
    id: 'sekerpatlat',
    title: 'Şeker Patlatma',
    tagline: 'Candy Crush tarzı: şekerleri dizip patlat, hedefi tuttur.',
    emoji: '🍬',
    href: 'games/sekerpatlat/index.html',
    tags: ['Arcade', 'Eşleştirme'],
    status: 'ready',
  },
  {
    id: 'balonpatlat',
    title: 'Bubble Shooter',
    tagline: 'Balonları nişanla, üçlü grupları patlat.',
    emoji: '🎈',
    href: 'games/balonpatlat/index.html',
    tags: ['Arcade', 'Nişan'],
    status: 'ready',
  },
  {
    id: 'blok',
    title: 'Blok Yerleştirme',
    tagline: 'Blokları yerleştir, satır ve sütunları doldurup temizle.',
    emoji: '🧱',
    href: 'games/blok/index.html',
    tags: ['Bulmaca', 'Sakin'],
    status: 'ready',
  },
  {
    id: 'domino',
    title: 'Domino Bulmacası',
    tagline: 'Taşları uç uca ekleyip bütün zinciri kur.',
    emoji: '🁣',
    href: 'games/domino/index.html',
    tags: ['Mantık', 'Klasik'],
    status: 'ready',
  },
  {
    id: 'mantikkapi',
    title: 'Mantık Kapıları',
    tagline: 'VE/VEYA/DEĞİL kapılarını çözüp hedef çıkışı yakala.',
    emoji: '⚡',
    href: 'games/mantikkapi/index.html',
    tags: ['Mantık', 'Zekâ'],
    status: 'ready',
  },
  {
    id: 'gruplama',
    title: 'Kelime Gruplama',
    tagline: 'On altı kelimeden ortak özellikli dörtlüleri bul.',
    emoji: '🧩',
    href: 'games/gruplama/index.html',
    tags: ['Kelime', 'Mantık'],
    status: 'ready',
  },
  {
    id: 'kopru',
    title: 'Köprü Kurma',
    tagline: 'Her adayı üstündeki sayı kadar köprüyle bağla.',
    emoji: '🌉',
    href: 'games/kopru/index.html',
    tags: ['Mantık', 'Bağlantı'],
    status: 'ready',
  },
  {
    id: 'arabacikar',
    title: 'Araba Çıkarma',
    tagline: 'Trafiği çözüp kırmızı arabayı çıkışa ulaştır.',
    emoji: '🚗',
    href: 'games/arabacikar/index.html',
    tags: ['Mantık', 'Klasik'],
    status: 'ready',
  },
  {
    id: 'sifre',
    title: 'Şifre Çözme',
    tagline: 'Sayıların arkasındaki gizli kelimeyi çöz.',
    emoji: '🔐',
    href: 'games/sifre/index.html',
    tags: ['Mantık', 'Kelime'],
    status: 'ready',
  },
  {
    id: 'pentomino',
    title: 'Pentomino',
    tagline: 'Beş kareli parçaları döndürüp kutuyu eksiksiz doldur.',
    emoji: '🟪',
    href: 'games/pentomino/index.html',
    tags: ['Bulmaca', 'Zekâ'],
    status: 'ready',
  },
  {
    id: 'farkbul',
    title: 'Farkları Bul',
    tagline: 'İki desen arasındaki beş farkı bul.',
    emoji: '🔍',
    href: 'games/farkbul/index.html',
    tags: ['Dikkat', 'Gözlem'],
    status: 'ready',
  },
  {
    id: 'tangram',
    title: 'Tangram',
    tagline: 'Parçaları çevirip hedef şeklin tamamını kapla.',
    emoji: '🔶',
    href: 'games/tangram/index.html',
    tags: ['Bulmaca', 'Şekil'],
    status: 'ready',
  },
  {
    id: 'kakuro',
    title: 'Kakuro',
    tagline: 'Rakamları topla, her dizinin hedefini tuttur.',
    emoji: '➕',
    href: 'games/kakuro/index.html',
    tags: ['Matematik', 'Mantık'],
    status: 'ready',
  },
  {
    id: 'gizlinesne',
    title: 'Gizli Nesne',
    tagline: 'Kalabalığın içine saklanan nesneleri bul.',
    emoji: '🔎',
    href: 'games/gizlinesne/index.html',
    tags: ['Dikkat', 'Gözlem'],
    status: 'ready',
  },
  {
    id: 'resimtamamla',
    title: 'Resim Tamamlama',
    tagline: 'Resimden eksilen parçayı seçeneklerden bul.',
    emoji: '🖼️',
    href: 'games/resimtamamla/index.html',
    tags: ['Dikkat', 'Gözlem'],
    status: 'ready',
  },
  {
    id: 'mahjong',
    title: 'Mahjong',
    tagline: 'Kenarı açık aynı taşları eşleştirip tahtayı boşalt.',
    emoji: '🀄',
    href: 'games/mahjong/index.html',
    tags: ['Eşleştirme', 'Sakin'],
    status: 'ready',
  },
  {
    id: 'zuma',
    title: 'Zuma',
    tagline: 'İlerleyen top zincirini üçlü gruplar patlatarak durdur.',
    emoji: '🐸',
    href: 'games/zuma/index.html',
    tags: ['Arcade', 'Nişan'],
    status: 'ready',
  },
  {
    id: 'solitaire',
    title: 'Solitaire',
    tagline: 'Klasik Klondike: dört rengi as’tan şaha diz.',
    emoji: '🃏',
    href: 'games/solitaire/index.html',
    tags: ['Kâğıt', 'Klasik'],
    status: 'ready',
  },
  {
    id: 'orumcek',
    title: 'Spider Solitaire',
    tagline: 'Şahtan as’a inen dizileri tamamlayıp tahtayı boşalt.',
    emoji: '🕷️',
    href: 'games/orumcek/index.html',
    tags: ['Kâğıt', 'Sabır'],
    status: 'ready',
  },
  {
    id: 'freecell',
    title: 'FreeCell',
    tagline: 'Dört boş hücreyi akıllı kullan, bütün kartları sırala.',
    emoji: '🂡',
    href: 'games/freecell/index.html',
    tags: ['Kâğıt', 'Mantık'],
    status: 'ready',
  },
  {
    id: 'rubik',
    title: 'Rubik Küpü',
    tagline: 'Açılmış küpte yüzleri çevirip altı rengi topla.',
    emoji: '🧊',
    href: 'games/rubik/index.html',
    tags: ['Bulmaca', 'Zekâ'],
    status: 'ready',
  },
]
